### ISSUE TITLE
Problem Extracting SNES Roms from sfrom

### ISSUE THREAD

**Issue by DylanJuran** [wheatevo/wiiu-vc-extractor#41]
About half of my SNES Classic ROMs aren't extracting. The error I get is 
`Unhandled Exception:
System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars`

**Comment by JDJGInc** [comment]
I have this same issue Too.

**Comment by KeenIIDX** [comment]
Same error here.  Full error is:

Unhandled Exception: System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)
   at System.IO.BinaryReader.InternalReadOneChar()
   at System.IO.BinaryReader.Read()
   at System.IO.BinaryReader.ReadChar()
   at WiiuVcExtractor.Libraries.EndianUtility.ReadNullTerminatedString(BinaryReader stream)
   at WiiuVcExtractor.Libraries.EndianUtility.ReadNullTerminatedString(Byte[] bytes)
   at WiiuVcExtractor.FileTypes.PkgHeader..ctor(String pkgFilePath)
   at WiiuVcExtractor.Program.Main(String[] args)

**Comment by KeenIIDX** [comment]
This broke with version 7.  Going back to 6 got me a working utility that generated ROMs with audio.

**Comment by wheatevo** [comment]
Thanks @KeenIIDX! I will take a look at what changed.

**Comment by wheatevo** [comment]
Release https://github.com/wheatevo/wiiu-vc-extractor/releases/tag/0.8.1 contains this fix.
